# -*- coding: utf-8 -*-
"""Calculadora Simples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gv-9idtzw1nf8SaWDIIW1PZfb-Vi2CXV
"""

def somar(a, b):
    return a + b

def subtrair(a, b):
    return a - b

def multiplicar(a, b):
    return a * b

def dividir(a, b):
    if b == 0:
        return "Não é possível dividir por zero!"
    return a / b

def calculadora():
    print('=======================================')
    print("Bem-vindo(a) à Calculadora em Python 🧮")
    print('=======================================')

    while True:
        print("\nEscolha uma operação:")
        print("1 - Somar")
        print("2 - Subtrair")
        print("3 - Multiplicar")
        print("4 - Dividir")
        print("0 - Sair")

        escolha = input("Digite a opção: ")

        if escolha == "0":
            print("Saindo... Até a próxima!")
            break

        if escolha not in ["1", "2", "3", "4"]:
            print("Opção inválida. Tente novamente.")
            continue

        try:
            num1 = float(input("Digite o primeiro número: "))
            num2 = float(input("Digite o segundo número: "))
        except ValueError:
            print("Entrada inválida! Por favor, digite números válidos.")
            continue

        if escolha == "1":
            resultado = somar(num1, num2)
        elif escolha == "2":
            resultado = subtrair(num1, num2)
        elif escolha == "3":
            resultado = multiplicar(num1, num2)
        elif escolha == "4":
            resultado = dividir(num1, num2)

        print(f"Resultado: {resultado}")

# Executar a calculadora
calculadora()